package br.com.lsi.ordemservico.JDialog.empresa;


import br.com.lsi.ordemservico.fachada.Facade;
import br.com.lsi.ordemservico.modelo.Empresa;
import br.com.lsi.ordemservico.modelo.Endereco;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Usuario
 */
public class RemoverEmpresaJDialog extends javax.swing.JDialog {

    DefaultTableModel modelo = new DefaultTableModel();

    private List<Empresa> listarEmpresa = new ArrayList();

    private Facade empresaFacade = new Facade();

    public RemoverEmpresaJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void preencherTabela() {

        modelo.setNumRows(0);
        Endereco endereco = new Endereco();

        try {
            List<Empresa> listarEmpresa = new ArrayList<Empresa>();
            listarEmpresa = empresaFacade.listarEmpresa();

            for (Empresa empresa : listarEmpresa) {

                modelo.addRow(new Object[]{empresa.getId(), empresa.getNomeFantasia(), empresa.getCNPJ(),
                    endereco.getId(), endereco.getRua(), endereco.getBairro(), endereco.getUf(),
                    endereco.getCidade(), endereco.getCep()

                }
                );

            }

            // e isso tem que ficar despois de tudo
            jTableExcluirEmpresa.setModel(modelo);

        } catch (Exception ex) {
            ex.printStackTrace();
            Logger.getLogger(EidtarEmpresaJDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableExcluirEmpresa = new javax.swing.JTable();
        jButtonExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableExcluirEmpresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableExcluirEmpresa);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 43, 620, 226));

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 110, 34));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed

        if (jTableExcluirEmpresa.getSelectedRow() == -1) {

            int linha = jTableExcluirEmpresa.getSelectedRow();

            int idEmpresa = (Integer) modelo.getValueAt(linha, 0);
            try {
                int resp = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Remover esse Livro ?", "removido", JOptionPane.YES_NO_OPTION);

                empresaFacade.removerEmpresa(idEmpresa);

                preencherTabela();
                // JOptionPane.showMessageDialog(null, MensagensUtil.getValor(MensagensUtil.MSG_REMOVIDO_SUCESSO, "Livro"));

            } catch (Exception ex) {
                Logger.getLogger(RemoverEmpresaJDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {

        modelo = (DefaultTableModel) jTableExcluirEmpresa.getModel();

        modelo.addColumn("ID");
        modelo.addColumn("NOME FANTASIA");
        modelo.addColumn("CNPJ");

        modelo.addColumn("IDENDERECO");
        modelo.addColumn("RUA");
        modelo.addColumn("BAIRRO");
        modelo.addColumn("UF");
        modelo.addColumn("CIDADE");
        modelo.addColumn("CEP");

        jTableExcluirEmpresa.getColumnModel().getColumn(0).setPreferredWidth(0);
        jTableExcluirEmpresa.getColumnModel().getColumn(0).setMaxWidth(0);
        jTableExcluirEmpresa.getColumnModel().getColumn(0).setMinWidth(0);

        jTableExcluirEmpresa.getColumnModel().getColumn(1).setPreferredWidth(700);
        jTableExcluirEmpresa.getColumnModel().getColumn(2).setPreferredWidth(600);

        jTableExcluirEmpresa.getColumnModel().getColumn(3).setPreferredWidth(500);
        jTableExcluirEmpresa.getColumnModel().getColumn(3).setPreferredWidth(400);
        jTableExcluirEmpresa.getColumnModel().getColumn(3).setPreferredWidth(700);

        jTableExcluirEmpresa.getColumnModel().getColumn(4).setPreferredWidth(750);
        jTableExcluirEmpresa.getColumnModel().getColumn(5).setPreferredWidth(0);
        jTableExcluirEmpresa.getColumnModel().getColumn(6).setMaxWidth(0);
        jTableExcluirEmpresa.getColumnModel().getColumn(7).setMinWidth(0);
        jTableExcluirEmpresa.getColumnModel().getColumn(8).setPreferredWidth(400);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoverEmpresaJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoverEmpresaJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoverEmpresaJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoverEmpresaJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RemoverEmpresaJDialog dialog = new RemoverEmpresaJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableExcluirEmpresa;
    // End of variables declaration//GEN-END:variables
}
