/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.lsi.ordemservico.swing;

import br.com.lsi.ordemservico.commom.exception.DAOException;
import br.com.lsi.ordemservico.enuns.TipoEmpresa;
import br.com.lsi.ordemservico.fachada.Fachada;
import br.com.lsi.ordemservico.modelo.Empresa;
import br.com.lsi.ordemservico.modelo.Endereco;
import javax.swing.JOptionPane;

/**
 *
 * @author Alan Santos Diniz
 */
public class EmpresaEdit extends javax.swing.JDialog {

    Fachada fachada = new Fachada();
    
    public Long id = null;

    /**
     * Creates new form EmpresaEdit
     */
    public EmpresaEdit(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void inserirEmpresa(Empresa emp) {

        txtId.setText(emp.getId().toString());
        txtNomeFantasia.setText(emp.getNomeFantasia());
        txtCnpj.setText(emp.getCNPJ());
        jComboBoxTipoEmpresa.setSelectedItem(emp.getTipoEmpresa());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblMarca2 = new javax.swing.JLabel();
        txtNomeFantasia = new javax.swing.JTextField();
        txtCnpj = new javax.swing.JTextField();
        lblMarca3 = new javax.swing.JLabel();
        jComboBoxTipoEmpresa = new javax.swing.JComboBox();
        lblMarca4 = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(450, 300));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblId.setText("ID:");
        jPanel1.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        txtId.setEnabled(false);
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 57, -1));

        lblMarca2.setText("Nome fantasia:");
        jPanel1.add(lblMarca2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        txtNomeFantasia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeFantasiaFocusLost(evt);
            }
        });
        jPanel1.add(txtNomeFantasia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 220, -1));

        txtCnpj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCnpjFocusLost(evt);
            }
        });
        jPanel1.add(txtCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 90, -1));

        lblMarca3.setText("Tipo Empresa:");
        jPanel1.add(lblMarca3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jComboBoxTipoEmpresa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Fornecedor", "Cliente" }));
        jComboBoxTipoEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoEmpresaActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxTipoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 130, -1));

        lblMarca4.setText("CNPJ:");
        jPanel1.add(lblMarca4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btCancelar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSalvar)
                    .addComponent(btCancelar)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed

        Empresa emp = new Empresa();
        
       
        emp.setNomeFantasia(txtNomeFantasia.getText());
        emp.setCNPJ(txtCnpj.getText());
        
        
        
  
        if (jComboBoxTipoEmpresa.getSelectedItem().equals("Fornecedor")) {
            emp.setTipoEmpresa(TipoEmpresa.FORNECEDOR);
        } else {
            emp.setTipoEmpresa(TipoEmpresa.CLIENTE);
        }


        if (id == null) {
            try {
                fachada.salvarEmpresas(emp);
                JOptionPane.showMessageDialog(null, "Salvo com Sucesso");

            } catch (DAOException ex) {
                ex.printStackTrace();
            }
        } else {
            try {
                emp.setId(id);
                fachada.atualizarEmpresas(emp);
                JOptionPane.showMessageDialog(null, "Atualizado com Sucesso");
            } catch (DAOException ex) {
                ex.printStackTrace();
            }
        }

        this.dispose();
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void txtNomeFantasiaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFantasiaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeFantasiaFocusLost

    private void txtCnpjFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCnpjFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCnpjFocusLost

    private void jComboBoxTipoEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoEmpresaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpresaEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpresaEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpresaEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpresaEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EmpresaEdit dialog = new EmpresaEdit(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox jComboBoxTipoEmpresa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMarca2;
    private javax.swing.JLabel lblMarca3;
    private javax.swing.JLabel lblMarca4;
    private javax.swing.JTextField txtCnpj;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNomeFantasia;
    // End of variables declaration//GEN-END:variables
}
