/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.lsi.ordemservico.swing;

import br.com.lsi.ordemservico.commom.exception.DAOException;
import br.com.lsi.ordemservico.fachada.Fachada;
import br.com.lsi.ordemservico.modelo.Equipamento;
import br.com.lsi.ordemservico.modelo.Funcionario;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alan Santos Diniz
 */
public class FuncionarioView extends javax.swing.JDialog {

    /**
     * Creates new form FuncionarioView
     */
    Fachada facade = new Fachada();

    public FuncionarioView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uJPanelImagem4 = new componentes.UJPanelImagem();
        btNovo = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtBuscarDesc = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtDados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(609, 334));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uJPanelImagem4.setImagem(new java.io.File("C:\\imagens\\2.jpg"));

        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btEdit.setText("Editar");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Função:");

        txtBuscarDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarDescActionPerformed(evt);
            }
        });
        txtBuscarDesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarDescKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout uJPanelImagem4Layout = new javax.swing.GroupLayout(uJPanelImagem4);
        uJPanelImagem4.setLayout(uJPanelImagem4Layout);
        uJPanelImagem4Layout.setHorizontalGroup(
            uJPanelImagem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uJPanelImagem4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscarDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        uJPanelImagem4Layout.setVerticalGroup(
            uJPanelImagem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uJPanelImagem4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(uJPanelImagem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btNovo)
                    .addComponent(btEdit)
                    .addComponent(btExcluir)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscarDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(uJPanelImagem4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, -1));

        jtDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "CPF", "SEXO", "FUNÇÃO", "DATA DE ADIMIÇÃO"
            }
        ));
        jtDados.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtDadosFocusGained(evt);
            }
        });
        jtDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtDadosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtDados);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 590, 250));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void preencherJtableFuncionario(List<Funcionario> lista) {

      

        DefaultTableModel modelo = (DefaultTableModel) jtDados.getModel();
        modelo.setNumRows(0);

        try {

            if (lista.size() > 0) {
                for (Funcionario funcionario : lista) {
                    modelo.addRow(new Object[]{funcionario.getId(), funcionario.getNome(), funcionario.getCpf(), funcionario.getSexo(), funcionario.getFuncao(), funcionario.getDateAdimicao()});
                }
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERRO AO LISTAR");
        }

    }


    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        FuncionarioEdit funcEdit = new FuncionarioEdit(null, true);
      
        funcEdit.setVisible(true);
    }//GEN-LAST:event_btNovoActionPerformed

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        int linhaSelecionada = jtDados.getSelectedRow();//pegando linha selecionada
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(null, "Funcionario Não Selecionado");
        }
        String id = (jtDados.getValueAt(linhaSelecionada, 0).toString());
        try {
            FuncionarioEdit funcEdit = new FuncionarioEdit(null, true);
            funcEdit.inserirFuncionario(facade.getByIdFuncionarios(Long.parseLong(id)));
             Funcionario func = new Funcionario();
            func = facade.getByIdFuncionarios(Long.parseLong(id));
            funcEdit.id = func.getId();
            funcEdit.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btEditActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        int linhaSelecionada = jtDados.getSelectedRow();//pegando linha selecionada
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(null, "Funcionario Não Selecionado");
        }
        String id = (jtDados.getValueAt(linhaSelecionada, 0).toString());
        int x = JOptionPane.showConfirmDialog(null, "Deseja Deletar");
        if (x == 0) {
            try {
                facade.deletarFuncionarios(facade.getByIdFuncionarios(Long.parseLong(id)));
                JOptionPane.showMessageDialog(null, "Excluido com Sucesso");
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showConfirmDialog(null, "Erro ao Excluir");
            }
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void jtDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtDadosMouseClicked

        if (evt.getClickCount() > 1) {
            System.out.println("clicou 2 vezes");
        }
    }//GEN-LAST:event_jtDadosMouseClicked

    private void jtDadosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtDadosFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jtDadosFocusGained

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        try {
            preencherJtableFuncionario(facade.getAllFuncionarios());
        } catch (DAOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         //Definindo o tamanho das colunas
        jtDados.getColumnModel().getColumn(0).setPreferredWidth(0);
        jtDados.getColumnModel().getColumn(1).setPreferredWidth(0);
        jtDados.getColumnModel().getColumn(2).setPreferredWidth(100);
        jtDados.getColumnModel().getColumn(3).setPreferredWidth(100);
        jtDados.getColumnModel().getColumn(4).setPreferredWidth(100);
        jtDados.getColumnModel().getColumn(5).setPreferredWidth(100);

        //Definindo tamanho 0 a coluna ID
        jtDados.getColumnModel().getColumn(1).setMinWidth(0);
    }//GEN-LAST:event_formWindowOpened

    private void txtBuscarDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarDescActionPerformed

    private void txtBuscarDescKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarDescKeyPressed
        List<Funcionario> listaf = new ArrayList<Funcionario>();
        //listaf = 
        
        preencherJtableFuncionario(listaf);
    }//GEN-LAST:event_txtBuscarDescKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FuncionarioView dialog = new FuncionarioView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btNovo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtDados;
    private javax.swing.JTextField txtBuscarDesc;
    private componentes.UJPanelImagem uJPanelImagem4;
    // End of variables declaration//GEN-END:variables
}
